#!/usr/bin/env python

from xtore.instance import ConsistentHashing
if __name__ == '__main__':
    my_ring = ConsistentHashing(1221, 2, 3)
    totoro = my_ring.appendData("tororo")
    data2 = my_ring.appendData("bambi")

    my_ring.searchKey(totoro.key)
    # my_ring.searchKey(Datum("no").key)
